---
title: "p8105_hw5_tt2714"
author: "Tiffany Tu"
date: "11/3/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr) 
library(purrr)
library(tidyr)
library(ggplot2)
library(ggrepel)
library(stringr)
```

## Problem 1
#### Create tidy dataframe with subject ID, arm, and results.
```{r message = FALSE}
data = data_frame(filename = list.files("data")) %>% 
  mutate(map(filename, ~ read_csv(file.path("data", .)))) %>% 
  unnest() %>% 
  separate(filename, c('arm', 'id'), sep = ".csv") %>%
  separate(arm, c('arm', 'id'), sep = "_") %>% 
  gather(week, everything(), -arm, -id) %>% 
  separate(week, c('x', 'week'), sep = "_") %>% 
  select(arm, id, week, value = "everything()") %>% 
  mutate(week = as.numeric(week))
```

#### Spaghetti plot
```{r}
data %>%
  ggplot(aes(x = week, y = value, colour = arm, 
             group = interaction(arm, id))) + 
  geom_text_repel(aes(label = ifelse(week > 7, id, "")), 
                  nudge_x = 0.4, size = 3) + 
  ggtitle("Control and Experimental Arms Over Time") + geom_line()
```
* comments 

     
## Problem 2
* comment on raw data
    
```{r message = FALSE}
homicide_citystate = read_csv(file = "./homicide-data.csv") %>% 
  unite(city_state, c(city, state), sep = ", ", remove = T) %>% 
  mutate(disposition = gsub('Closed by arrest', 'homicide', disposition), 
         disposition = gsub('Closed without arrest|Open/No arrest', 'unsolved', disposition)) %>% 
  group_by(city_state, disposition) %>% 
  summarize(count = n())
```

